// Generated from i18n-iso-countries (ISO 3166-1 codes + Spanish names).
// Static lookup so we don't ship a full i18n library just for this map.
export const ALPHA2_TO_ALPHA3: Record<string, string> = {
  AD: "AND",
  AE: "ARE",
  AF: "AFG",
  AG: "ATG",
  AI: "AIA",
  AL: "ALB",
  AM: "ARM",
  AO: "AGO",
  AQ: "ATA",
  AR: "ARG",
  AS: "ASM",
  AT: "AUT",
  AU: "AUS",
  AW: "ABW",
  AX: "ALA",
  AZ: "AZE",
  BA: "BIH",
  BB: "BRB",
  BD: "BGD",
  BE: "BEL",
  BF: "BFA",
  BG: "BGR",
  BH: "BHR",
  BI: "BDI",
  BJ: "BEN",
  BL: "BLM",
  BM: "BMU",
  BN: "BRN",
  BO: "BOL",
  BQ: "BES",
  BR: "BRA",
  BS: "BHS",
  BT: "BTN",
  BV: "BVT",
  BW: "BWA",
  BY: "BLR",
  BZ: "BLZ",
  CA: "CAN",
  CC: "CCK",
  CD: "COD",
  CF: "CAF",
  CG: "COG",
  CH: "CHE",
  CI: "CIV",
  CK: "COK",
  CL: "CHL",
  CM: "CMR",
  CN: "CHN",
  CO: "COL",
  CR: "CRI",
  CU: "CUB",
  CV: "CPV",
  CW: "CUW",
  CX: "CXR",
  CY: "CYP",
  CZ: "CZE",
  DE: "DEU",
  DJ: "DJI",
  DK: "DNK",
  DM: "DMA",
  DO: "DOM",
  DZ: "DZA",
  EC: "ECU",
  EE: "EST",
  EG: "EGY",
  EH: "ESH",
  ER: "ERI",
  ES: "ESP",
  ET: "ETH",
  FI: "FIN",
  FJ: "FJI",
  FK: "FLK",
  FM: "FSM",
  FO: "FRO",
  FR: "FRA",
  GA: "GAB",
  GB: "GBR",
  GD: "GRD",
  GE: "GEO",
  GF: "GUF",
  GG: "GGY",
  GH: "GHA",
  GI: "GIB",
  GL: "GRL",
  GM: "GMB",
  GN: "GIN",
  GP: "GLP",
  GQ: "GNQ",
  GR: "GRC",
  GS: "SGS",
  GT: "GTM",
  GU: "GUM",
  GW: "GNB",
  GY: "GUY",
  HK: "HKG",
  HM: "HMD",
  HN: "HND",
  HR: "HRV",
  HT: "HTI",
  HU: "HUN",
  ID: "IDN",
  IE: "IRL",
  IL: "ISR",
  IM: "IMN",
  IN: "IND",
  IO: "IOT",
  IQ: "IRQ",
  IR: "IRN",
  IS: "ISL",
  IT: "ITA",
  JE: "JEY",
  JM: "JAM",
  JO: "JOR",
  JP: "JPN",
  KE: "KEN",
  KG: "KGZ",
  KH: "KHM",
  KI: "KIR",
  KM: "COM",
  KN: "KNA",
  KP: "PRK",
  KR: "KOR",
  KW: "KWT",
  KY: "CYM",
  KZ: "KAZ",
  LA: "LAO",
  LB: "LBN",
  LC: "LCA",
  LI: "LIE",
  LK: "LKA",
  LR: "LBR",
  LS: "LSO",
  LT: "LTU",
  LU: "LUX",
  LV: "LVA",
  LY: "LBY",
  MA: "MAR",
  MC: "MCO",
  MD: "MDA",
  ME: "MNE",
  MF: "MAF",
  MG: "MDG",
  MH: "MHL",
  MK: "MKD",
  ML: "MLI",
  MM: "MMR",
  MN: "MNG",
  MO: "MAC",
  MP: "MNP",
  MQ: "MTQ",
  MR: "MRT",
  MS: "MSR",
  MT: "MLT",
  MU: "MUS",
  MV: "MDV",
  MW: "MWI",
  MX: "MEX",
  MY: "MYS",
  MZ: "MOZ",
  NA: "NAM",
  NC: "NCL",
  NE: "NER",
  NF: "NFK",
  NG: "NGA",
  NI: "NIC",
  NL: "NLD",
  NO: "NOR",
  NP: "NPL",
  NR: "NRU",
  NU: "NIU",
  NZ: "NZL",
  OM: "OMN",
  PA: "PAN",
  PE: "PER",
  PF: "PYF",
  PG: "PNG",
  PH: "PHL",
  PK: "PAK",
  PL: "POL",
  PM: "SPM",
  PN: "PCN",
  PR: "PRI",
  PS: "PSE",
  PT: "PRT",
  PW: "PLW",
  PY: "PRY",
  QA: "QAT",
  RE: "REU",
  RO: "ROU",
  RS: "SRB",
  RU: "RUS",
  RW: "RWA",
  SA: "SAU",
  SB: "SLB",
  SC: "SYC",
  SD: "SDN",
  SE: "SWE",
  SG: "SGP",
  SH: "SHN",
  SI: "SVN",
  SJ: "SJM",
  SK: "SVK",
  SL: "SLE",
  SM: "SMR",
  SN: "SEN",
  SO: "SOM",
  SR: "SUR",
  SS: "SSD",
  ST: "STP",
  SV: "SLV",
  SX: "SXM",
  SY: "SYR",
  SZ: "SWZ",
  TC: "TCA",
  TD: "TCD",
  TF: "ATF",
  TG: "TGO",
  TH: "THA",
  TJ: "TJK",
  TK: "TKL",
  TL: "TLS",
  TM: "TKM",
  TN: "TUN",
  TO: "TON",
  TR: "TUR",
  TT: "TTO",
  TV: "TUV",
  TW: "TWN",
  TZ: "TZA",
  UA: "UKR",
  UG: "UGA",
  UM: "UMI",
  US: "USA",
  UY: "URY",
  UZ: "UZB",
  VA: "VAT",
  VC: "VCT",
  VE: "VEN",
  VG: "VGB",
  VI: "VIR",
  VN: "VNM",
  VU: "VUT",
  WF: "WLF",
  WS: "WSM",
  XK: "XKK",
  YE: "YEM",
  YT: "MYT",
  ZA: "ZAF",
  ZM: "ZMB",
  ZW: "ZWE",
};

export const ALPHA2_TO_NAME_ES: Record<string, string> = {
  AD: "Andorra",
  AE: "Emiratos Árabes Unidos",
  AF: "Afganistán",
  AG: "Antigua y Barbuda",
  AI: "Anguila",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antártida",
  AR: "Argentina",
  AS: "Samoa Americana",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Islas Åland",
  AZ: "Azerbaiyán",
  BA: "Bosnia y Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Bélgica",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrein",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermudas",
  BN: "Brunei Darussalam",
  BO: "Bolivia",
  BQ: "Bonaire, San Eustaquio y Saba",
  BR: "Brasil",
  BS: "Bahamas",
  BT: "Bután",
  BV: "Isla Bouvet",
  BW: "Botswana",
  BY: "Bielorrusia",
  BZ: "Belice",
  CA: "Canadá",
  CC: "Islas Cocos (Keeling)",
  CD: "Congo (República Democrática del)",
  CF: "República Centroafricana",
  CG: "Congo",
  CH: "Suiza",
  CI: "Costa de Marfil",
  CK: "Islas Cook",
  CL: "Chile",
  CM: "Camerún",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Isla de Navidad",
  CY: "Chipre",
  CZ: "República Checa",
  DE: "Alemania",
  DJ: "Yibuti",
  DK: "Dinamarca",
  DM: "Dominica",
  DO: "República Dominicana",
  DZ: "Argelia",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egipto",
  EH: "Sahara Occidental",
  ER: "Eritrea",
  ES: "España",
  ET: "Etiopía",
  FI: "Finlandia",
  FJ: "Fiji",
  FK: "Islas Malvinas",
  FM: "Micronesia",
  FO: "Islas Feroe",
  FR: "Francia",
  GA: "Gabón",
  GB: "Reino Unido",
  GD: "Granada",
  GE: "Georgia",
  GF: "Guayana Francesa",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Groenlandia",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadalupe",
  GQ: "Guinea Ecuatorial",
  GR: "Grecia",
  GS: "Georgia del Sur y las Islas Sandwich del Sur",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard e Islas McDonald",
  HN: "Honduras",
  HR: "Croacia",
  HT: "Haití",
  HU: "Hungría",
  ID: "Indonesia",
  IE: "Irlanda",
  IL: "Israel",
  IM: "Isla de Man",
  IN: "India",
  IO: "Territorio Británico del Océano Índico",
  IQ: "Iraq",
  IR: "Irán",
  IS: "Islandia",
  IT: "Italia",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordania",
  JP: "Japón",
  KE: "Kenia",
  KG: "Kirguistán",
  KH: "Camboya",
  KI: "Kiribati",
  KM: "Comoras",
  KN: "Saint Kitts y Nevis",
  KP: "República Popular Democrática de Corea",
  KR: "República de Corea",
  KW: "Kuwait",
  KY: "Islas Caimán",
  KZ: "Kazajistán",
  LA: "República Democrática Popular de Lao",
  LB: "Líbano",
  LC: "Santa Lucía",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesoto",
  LT: "Lituania",
  LU: "Luxemburgo",
  LV: "Letonia",
  LY: "Libia",
  MA: "Marruecos",
  MC: "Mónaco",
  MD: "Moldavia",
  ME: "Montenegro",
  MF: "Saint Martin (francesa)",
  MG: "Madagascar",
  MH: "Islas Marshall",
  MK: "Macedonia del Norte",
  ML: "Malí",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Islas Marianas del Norte",
  MQ: "Martinica",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauricio",
  MV: "Maldivas",
  MW: "Malaui",
  MX: "México",
  MY: "Malasia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "Nueva Caledonia",
  NE: "Níger",
  NF: "Isla Norfolk",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Países Bajos",
  NO: "Noruega",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "Nueva Zelanda",
  OM: "Omán",
  PA: "Panamá",
  PE: "Perú",
  PF: "Polinesia Francesa",
  PG: "Papua Nueva Guinea",
  PH: "Filipinas",
  PK: "Pakistán",
  PL: "Polonia",
  PM: "San Pedro y Miquelón",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestina",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Catar",
  RE: "Reunión",
  RO: "Rumanía",
  RS: "Serbia",
  RU: "Rusia",
  RW: "Ruanda",
  SA: "Arabia Saudita",
  SB: "Islas Salomón",
  SC: "Seychelles",
  SD: "Sudán",
  SE: "Suecia",
  SG: "Singapur",
  SH: "Santa Helena, Ascensión y Tristán de Acuña",
  SI: "Eslovenia",
  SJ: "Svalbard y Jan Mayen",
  SK: "Eslovaquia",
  SL: "Sierra Leona",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "Sudán del Sur",
  ST: "Santo Tomé y Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten (neerlandesa)",
  SY: "República Árabe Siria",
  SZ: "Esuatini",
  TC: "Islas Turcas y Caicos",
  TD: "Chad",
  TF: "Tierras Australes Francesas",
  TG: "Togo",
  TH: "Tailandia",
  TJ: "Tayikistán",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistán",
  TN: "Túnez",
  TO: "Tonga",
  TR: "Turquía",
  TT: "Trinidad y Tobago",
  TV: "Tuvalu",
  TW: "Taiwán",
  TZ: "Tanzania",
  UA: "Ucrania",
  UG: "Uganda",
  UM: "Islas Ultramarinas Menores de los Estados Unidos",
  US: "Estados Unidos",
  UY: "Uruguay",
  UZ: "Uzbekistán",
  VA: "Santa Sede",
  VC: "San Vicente y las Granadinas",
  VE: "Venezuela",
  VG: "Islas Vírgenes británicas",
  VI: "Islas Vírgenes de los Estados Unidos",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis y Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "Sudáfrica",
  ZM: "Zambia",
  ZW: "Zimbabue",
};

export const ALPHA3_TO_ALPHA2: Record<string, string> = Object.fromEntries(
  Object.entries(ALPHA2_TO_ALPHA3).map(([a2, a3]) => [a3, a2])
);
